[package]
name = "ingest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
domain = { path = "../domain" }
extract = { path = "../extract" }
thiserror = { workspace = true }

[dev-dependencies]
pdf-fixtures = { path = "../pdf-fixtures" }

[lints]
workspace = true
